src/JD/JolydaysBundle/Entity/Illustrations.php
<?php

namespace JD\JolydaysBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\UploadedFile;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * Illustrations
 *
 * @ORM\Table(name="illustrations")
 * @ORM\Entity(repositoryClass="JD\JolydaysBundle\Repository\IllustrationsRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Illustrations
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="src", type="string", length=255)
     */
    private $src;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set src
     *
     * @param string $src
     *
     * @return Illustrations
     */
    public function setSrc($src)
    {
        $this->src = $src;

        return $this;
    }

    /**
     * Get src
     *
     * @return string
     */
    public function getSrc()
    {
        return $this->src;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Illustrations
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    private $file;

    private $saveName;

    public function setFile(UploadedFile $file)
    {
      $this->file = $file;

      // Check if a file has already been uploaded
      // => temporarily save file name and initialise attributes
      if (null !== $this->src) {
        $this->saveName = $this->src; 
        $this->src = null;
        $this->alt = null; 
      }
    }

    public function getFile() {
      return $this->file;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function preUpload()
    {
      // if no uploaded file, return
      if (null === $this->file) {
        return;
      }
      
      // get file extension
      $this->src = $this->file->guessExtension();

      // same name as original
      $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist
     * @ORM\PostUpdate
     */
    public function upload()
    {
      // if no uploaded file, return
      if (null === $this->file) {
        return;
      }

      // if already has file, delete ancient file
      if (null !== $this->saveName) {
        $ancientFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->saveName;
        if (file_exists($ancientFile)) {
          unlink($ancientFile);
        }
      }
      // move new file to upload root directory as id.src
      $this->file->move( $this->getUploadRootDir(), $this->id.'.'.$this->src );
    }

    /**
     * @ORM\PreRemove
     */
    public function preRemoveUpload()
    {
      // save name (remove = remove id)
      $this->saveName = $this->getUploadRootDir().'/'.$this->id.'.'.$this->src;
    }

    /**
     * @ORM\PostRemove
     */
    public function removeUpload()
    {
      // delete file definitely by its name
      if (file_exists($this->saveName)) {
        unlink($this->saveName);
      }
    }

    public function getUploadDir()
    {
      return 'uploads/img';
    }

    public function getWebDir(){
      return $this->getUploadDir().'/'.$this->getId().'.'.$this->getSrc();
    }

    protected function getUploadRootDir()
    {
      return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

}

src/JD/JolydaysBundle/Entity/Posts.php
<?php

namespace JD\JolydaysBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Posts
 *
 * @ORM\Table(name="posts")
 * @ORM\Entity(repositoryClass="JD\JolydaysBundle\Repository\PostsRepository")
 */
class Posts
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="author", type="string", length=255)
     */
    private $author;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="string", length=255)
     */
    private $content;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date", type="datetime")
     */
    private $date;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Posts
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set author
     *
     * @param string $author
     *
     * @return Posts
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set content
     *
     * @param string $content
     *
     * @return Posts
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Posts
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @ORM\OneToOne(targetEntity="JD\JolydaysBundle\Entity\Illustrations", cascade={"persist","remove"})
     */
    private $image;

    /**
     * Set image
     *
     * @param \JD\JolydaysBundle\Entity\Illustrations $image
     *
     * @return Posts
     */
    public function setImage(\JD\JolydaysBundle\Entity\Illustrations $image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return \JD\JolydaysBundle\Entity\Illustrations
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @ORM\ManyToMany(targetEntity="JD\JolydaysBundle\Entity\Category", cascade={"persist"}, inversedBy="posts")
     * 
     */
    private $categories;

    /**
     * Add category
     *
     * @param \JD\JolydaysBundle\Entity\Category $category
     *
     * @return Posts
     */
    public function addCategory(\JD\JolydaysBundle\Entity\Category $category)
    {
        $this->categories[] = $category;

        return $this;
    }

    /**
     * Remove category
     *
     * @param \JD\JolydaysBundle\Entity\Category $category
     */
    public function removeCategory(\JD\JolydaysBundle\Entity\Category $category)
    {
        $this->categories->removeElement($category);
    }

    /**
     * Get categories
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    // default constructor to current 
    public function __construct()
    {
        $this->date = new \Datetime();
        $this->categories = new \Doctrine\Common\Collections\ArrayCollection();
    }
}

src/JD/JolydaysBundle/Form/PostsType.php
<?php

namespace JD\JolydaysBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PostsType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date', DateType::class)
            ->add('title')
            ->add('content', TextareaType::class)
            ->add('author')
            ->add('image', IllustrationsType::class)
            ->add('categories', EntityType::class, array(
                'class'   => 'JDJolydaysBundle:Category',
                'choice_label' => 'name',
                'multiple'     => true,
                'expanded'       => false,
                ))
            ->add('save',      SubmitType::class);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'JD\JolydaysBundle\Entity\Posts'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'jd_jolydaysbundle_posts';
    }


}

src/JD/JolydaysBundle/Controller/PostsController.php
<?php

namespace JD\JolydaysBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\Request;
use JD\JolydaysBundle\Entity\Posts;
use JD\JolydaysBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

use JD\JolydaysBundle\Form\PostsType;
use JD\JolydaysBundle\Form\PostsEditType;
use JD\JolydaysBundle\Repository\CategoryRepository;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\SearchType;

class PostsController extends Controller
{
  // path /
  public function indexAction($page)
  {
    // get all posts
    $repository = $this->getDoctrine()->getManager()->getRepository('JDJolydaysBundle:Posts');
    $posts = $repository->findAll();    

    return $this->render('JDJolydaysBundle:Posts:index.html.twig', array(
      'page_title' => 'All posts',
      'posts' => $posts
    ));
  }

  // path /post/$post_id, $post_id is from url
  public function viewAction($post_id)
  {
    $repository = $this
      ->getDoctrine()
      ->getManager()
      ->getRepository('JDJolydaysBundle:Posts');

    $post = $repository->find($post_id); 
    $categs = $post->getCategories();
    if ( null !== $post){
      // Call view.html.twig and send post parameter
      return $this->render('JDJolydaysBundle:Posts:view.html.twig', array(
        'post' => $post,
        'categories' => $categs
      ));
    }else{
      throw new NotFoundHttpException('This post does not exist');
    }
    
  }

  // path /add
  public function addAction(Request $request)
  {
    $post = new Posts();

    // create the form
    $form = $this->createForm(PostsType::class, $post);

    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

      if ($form->isValid()) {
        $em = $this->getDoctrine()->getManager();
        $em->persist($post);
        $em->flush();

        return $this->redirectToRoute('jd_jolydays_view', array(
          'post_id' => $post->getId()
          ));
      }

    }

    return $this->render('JDJolydaysBundle:Posts:add.html.twig', array(
      'form' => $form->createView()
    ));
  }

  // path /edit/$post_id_to_edit
  public function editAction($post_id, Request $request)
  {
    $em = $this->getDoctrine()->getManager();
    $post = $em->getRepository('JDJolydaysBundle:Posts')->find($post_id);

    if (null === $post) {
      throw new NotFoundHttpException("This post does not exist");
    }

    $form = $this->createForm(PostsEditType::class, $post);

    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
      $em->flush();

      return $this->redirectToRoute('jd_jolydays_view', array(
          'post_id' => $post_id
          ));
    }
    
    // show the edit form
    return $this->render('JDJolydaysBundle:Posts:edit.html.twig',array(
      'post_id'=> $post->getId(),
      'form' => $form->createView()
      ));
      
  }

  // path /delete/$post_id_to_delete
  public function deleteAction($post_id, Request $request)
  {
    $em = $this->getDoctrine()->getManager();
    $post = $em->getRepository('JDJolydaysBundle:Posts')->find($post_id);

    if (null === $post) {
      throw new NotFoundHttpException("This post does not exist");
    }

    if ($request->isMethod('POST')) {
      $em->remove($post);
      $em->flush();
      return $this->redirectToRoute('jd_jolydays_homepage');
    }

    //show the page confirming deletion
    return $this->render('JDJolydaysBundle:Posts:delete.html.twig', array('post_id' => $post_id ));
  }

  public function menuAction()
  {
    // Get all categories
    $repository = $this->getDoctrine()->getManager()->getRepository('JDJolydaysBundle:Category');
    $categories = $repository->findAll();
    // Pass parameters to the view
    return $this->render('JDJolydaysBundle:Posts:categories.html.twig', array(
        'categories' => $categories
      ));
  }

  public function postsInCatAction($cat_name, Request $request) {
    $cat_name = $request->attributes->get('cat_name');
    
    $categories = $this
                  ->getDoctrine()
                  ->getManager()
                  ->getRepository('JDJolydaysBundle:Category');
    $category = $categories->findOneBy(
        array('name' => $cat_name)
      );

    $posts = $category->getPosts(); 
    
    return $this->render('JDJolydaysBundle:Posts:index.html.twig', array(
      'page_title' => 'All posts in '.$cat_name.' category',
        'posts' => $posts
      ));
  }

  public function searchAction(Request $request)
  {
    $search = NULL; 
    $form = $this->createFormBuilder()
        ->setAction($this->generateUrl('jd_jolydays_result', array('search' => $search) ))
        ->add('search', SearchType::class)
        ->add('Find', SubmitType::class)
        ->getForm();
    
    if ($request->isMethod('POST') && $form->handleRequest($request)->isValid())
    { 
      $search = $request->request->get('form')['search'];

      $repository = $this
                  ->getDoctrine()
                  ->getManager()
                  ->getRepository('JDJolydaysBundle:Posts');
                  
      $query = $repository->createQueryBuilder('p')
        ->where('p.title LIKE :result_title')
        ->setParameter('result_title', '%'.$search.'%')

        ->orWhere('p.author LIKE :result_author')
        ->setParameter('result_author', '%'.$search.'%')

        ->orWhere('p.content LIKE :result_content')
        ->setParameter('result_content', '%'.$search.'%')

        ->getQuery(); 

      $query = $query->getResult();

      return $this->render('JDJolydaysBundle:Posts:index.html.twig', array(
        'page_title' => 'Search result for "'.$search.'" keyword',
        'posts' => $query
        ));
    }   

    return $this->render('JDJolydaysBundle:Posts:resultForm.html.twig', array(
      'form' => $form->createView()
    ));
  }
}

src/JD/JolydaysBundle/Resources/views/Posts/add.html.twig
{# Template of adding post  #}

{% extends "JDJolydaysBundle::layout.html.twig" %}

{% block title %}
  Add post - {{ parent() }}
{% endblock %}

{% block jolydaysbundle_body %}

  <h2>Add post</h2>

  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  <div class="form-group">
    {{ form_label(form.date, "Date", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.date) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.title, "Title", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.content, "Content", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    <div class="col-sm-10">
      {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.author, "Author", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.author) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.image, "Image", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.image) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.categories, "Select categories", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.categories) }}
    </div>
  </div>

  
  <div class="form-group text-right">
  	<div class="col-sm-10 col-sm-offset-2">
	  	{# {{ form_rest(form) }} #}
	  	{{ form_widget(form.save, {'attr': {'class': 'btn btn-success'}}) }}
  	</div>
	</div>
  {{ form_end(form) }}

{% endblock %}

src/JD/JolydaysBundle/Resources/views/Posts/categories.html.twig
<div class="nav nav-pills nav-stacked">
	{% for category in categories %}
			<a href="{{ path('jd_jolydays_posts_in_cat', {'cat_name': category.name}) }}" title="" class="btn btn-default btn-xs">{{ category.name }}</a>
	{% else %}
		No category yet
	{% endfor %}
</div>

src/JD/JolydaysBundle/Resources/views/Posts/delete.html.twig
{# Template of deleting post #}
{% extends "JDJolydaysBundle::layout.html.twig" %}

{% block title %}
  {{ parent() }}
{% endblock %}

{% block jolydaysbundle_body %}

  <h4>Confirm deletion ?</h4>

  <form action="{{ path('jd_jolydays_delete', {'post_id': post_id}) }}" method="post">
    <a href="{{ path('jd_jolydays_view', {'post_id': post_id}) }}" class="btn">
      Back to post
    </a>
    <input type="submit" value="Delete" class="btn btn-danger" />
  </form>

{% endblock %}

src/JD/JolydaysBundle/Resources/views/Posts/edit.html.twig
{# Template of editing post  #}

{% extends "JDJolydaysBundle::layout.html.twig" %}

{% block title %}
  Edit post - {{ parent() }}
{% endblock %}

{% block jolydaysbundle_body %}

  <h4>Edit post</h4>

  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

  <div class="form-group">
    {{ form_label(form.title, "Title", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.content, "Content", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    <div class="col-sm-10">
      {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.author, "Author", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.author) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.image, "Image", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.image) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.categories, "Select categories", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    <div class="col-sm-10">
      {{ form_widget(form.categories) }}
    </div>
  </div>

  
  <div class="form-group text-right">
  	<div class="col-sm-10 col-sm-offset-2">
	  	{# {{ form_rest(form) }} #}
	  	{{ form_widget(form.save, {'attr': {'class': 'btn btn-success'}}) }}
  	</div>
	</div>
  {{ form_end(form) }}

{% endblock %}

src/JD/JolydaysBundle/Resources/views/Posts/index.html.twig
{# Hompage template - list of all posts #}
{% extends "JDJolydaysBundle::layout.html.twig" %}

{% block title %}
  {{ parent() }}
{% endblock %}

{% block jolydaysbundle_body %}

  {% block page_title %}
    <h2>{{ page_title }}</h2>
  {% endblock %}

  <ul class="list-posts">
    {% for post in posts %}
      <li>
        <a href="{{ path('jd_jolydays_view', {'post_id': post.id}) }}">
          {{ post.title }}
        </a>
      </li>
    {% else %}
      <li>0 post</li>
    {% endfor %}
  </ul>

{% endblock %}

src/JD/JolydaysBundle/Resources/views/Posts/result.html.twig
{# Hompage template - list of all posts #}
{% extends "JDJolydaysBundle::layout.html.twig" %}

{% block title %}
  {{ parent() }}
{% endblock %}

{% block jolydaysbundle_body %}

  {% block page_title %}
    <h2>All posts</h2>
  {% endblock %}

  <ul>
    {% for post in posts %}
      <li>
        <a href="{{ path('jd_jolydays_view', {'post_id': post.id}) }}">
          {{ post.title }}
        </a>
      </li>
    {% else %}
      <li>0 post</li>
    {% endfor %}
  </ul>

{% endblock %}

src/JD/JolydaysBundle/Resources/views/Posts/resultForm.html.twig
<div class="col-sm-6 text-right">
    {{ form_start(form, { 'attr': {'class': 'form-inline'} }) }}
        <div class="form-group">
        	<div class="input-group">
            {{ form_widget(form.search, { 'attr': {'class': "form-control", 'placeholder':"keyword", 'autocomplete':"off"} }) }}
        	</div>
        </div>
        {{ form_widget(form.Find, { 'attr': {'class': 'btn btn-primary'} }) }}

    {{ form_rest(form) }}
    {{ form_end(form) }}
</div>

src/JD/JolydaysBundle/Resources/views/Posts/view.html.twig
{# Template of a single post  #}
{% extends "JDJolydaysBundle::layout.html.twig" %}

{% block title %}
  View post - {{ parent() }}
{% endblock %}

{% block jolydaysbundle_body %}

  {# vars are from controller #}
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4 text-center">
      <img src="{{ asset(post.image.webDir) }}" alt="{{post.image.alt}}" class="img-thumbnail" />
    </div>
    <div class="col-sm-12 text-justify">
       {% block page_title %}
        <h2 class="text-center">{{ post.title }}</h2>
      {% endblock %}
      <div class="col-sm-12">{{ post.content }}</div>
      <div class="col-sm-12 metadata-wrap">
        Posted by <span class="text-success">{{ post.author | upper }}</span> on <span class="text-success">{{ post.date|date('d/m/Y') }}</span>
      </div>
      <div class="col-sm-12 tags-wrap">
        <div class="row">
          <div class="col-sm-2">
            In categories:
          </div>
          <div class="col-sm-10">
            <ul class="list-inline">
              {% for category in categories %}
                <li>
                  <a href="{{ path('jd_jolydays_posts_in_cat', {'cat_name': category.name}) }}" title="" class="btn btn-default btn-xs">{{ category.name }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-12">
      <a href="{{ path('jd_jolydays_homepage') }}" class="btn btn-default btn-xs">
        All posts
      </a>
      <a href="{{ path('jd_jolydays_edit', {'post_id': post.id}) }}" class="btn btn-default btn-xs">
        Edit
      </a>
      <a href="{{ path('jd_jolydays_delete', {'post_id': post.id}) }}" class="btn btn-danger btn-xs">
        Delete
      </a>
    </div>
  </div>

{% endblock %}